# Generated by Django 3.0.5 on 2020-05-12 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Країна')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Країну',
                'verbose_name_plural': 'Країни',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=150, verbose_name='Стать')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Стать',
                'verbose_name_plural': 'Стать',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тема')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Тему',
                'verbose_name_plural': 'Теми',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Рік')),
            ],
            options={
                'verbose_name': 'Рік',
                'verbose_name_plural': 'Рік',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Country', verbose_name='Країна')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Sex', verbose_name='Стать')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Користувача',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('file', models.FileField(upload_to='file/', verbose_name='Файл')),
                ('presence', models.BooleanField(default=False, verbose_name='Виступав на конференції')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Theme', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('year', models.ForeignKey(default=1712715696, on_delete=django.db.models.deletion.CASCADE, to='register.Year', verbose_name='Рік')),
            ],
            options={
                'verbose_name': 'Статтю',
                'verbose_name_plural': 'Статті',
            },
        ),
    ]
