# Generated by Django 3.0.5 on 2020-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200513_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='presence',
            field=models.BooleanField(choices=[('Виступали', 'Виступали'), ('Не виступали', 'Не виступали')], default='Не виступали', verbose_name='Виступав на конференції'),
        ),
    ]
