# Generated by Django 3.0.5 on 2020-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200513_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='presence',
            field=models.CharField(choices=[('Виступали', 'Виступали'), ('Не виступали', 'Не виступали')], default='Не виступали', max_length=15, verbose_name='Виступав на конференції'),
        ),
    ]
